name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag webapp

    - name: Login to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA }}'

    - name: Deploy to CloudRun
      run: |
        gcloud run deploy webapp --region europe-west1 --image webapp --platform managed --allow-unauthenticated --project hostspacecloud
